name: run-tests
on: pull_request
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo systemctl start mysql.service
      - run: pip3 install -r requirements.txt
      - run: echo -e "user = \"root\"\npassword = \"root\"\nemail_config = {}" > config.py
      - run: python3 -m unittest
